// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trusted/v1/request_response.proto

package trustedv1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                []byte   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{0}
}
func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *HealthCheckResponse) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

type AddTxRequest struct {
	Txdata               []byte   `protobuf:"bytes,1,opt,name=txdata,proto3" json:"txdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTxRequest) Reset()         { *m = AddTxRequest{} }
func (m *AddTxRequest) String() string { return proto.CompactTextString(m) }
func (*AddTxRequest) ProtoMessage()    {}
func (*AddTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{1}
}
func (m *AddTxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTxRequest.Unmarshal(m, b)
}
func (m *AddTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTxRequest.Marshal(b, m, deterministic)
}
func (m *AddTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTxRequest.Merge(m, src)
}
func (m *AddTxRequest) XXX_Size() int {
	return xxx_messageInfo_AddTxRequest.Size(m)
}
func (m *AddTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTxRequest proto.InternalMessageInfo

func (m *AddTxRequest) GetTxdata() []byte {
	if m != nil {
		return m.Txdata
	}
	return nil
}

type AddTxResponse struct {
	Txhash               []byte   `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTxResponse) Reset()         { *m = AddTxResponse{} }
func (m *AddTxResponse) String() string { return proto.CompactTextString(m) }
func (*AddTxResponse) ProtoMessage()    {}
func (*AddTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{2}
}
func (m *AddTxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTxResponse.Unmarshal(m, b)
}
func (m *AddTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTxResponse.Marshal(b, m, deterministic)
}
func (m *AddTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTxResponse.Merge(m, src)
}
func (m *AddTxResponse) XXX_Size() int {
	return xxx_messageInfo_AddTxResponse.Size(m)
}
func (m *AddTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTxResponse proto.InternalMessageInfo

func (m *AddTxResponse) GetTxhash() []byte {
	if m != nil {
		return m.Txhash
	}
	return nil
}

func (m *AddTxResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{3}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	Pending              uint64   `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	Queue                uint64   `protobuf:"varint,2,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{4}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetPending() uint64 {
	if m != nil {
		return m.Pending
	}
	return 0
}

func (m *StatusResponse) GetQueue() uint64 {
	if m != nil {
		return m.Queue
	}
	return 0
}

type ResetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetRequest) Reset()         { *m = ResetRequest{} }
func (m *ResetRequest) String() string { return proto.CompactTextString(m) }
func (*ResetRequest) ProtoMessage()    {}
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{5}
}
func (m *ResetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetRequest.Unmarshal(m, b)
}
func (m *ResetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetRequest.Marshal(b, m, deterministic)
}
func (m *ResetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetRequest.Merge(m, src)
}
func (m *ResetRequest) XXX_Size() int {
	return xxx_messageInfo_ResetRequest.Size(m)
}
func (m *ResetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetRequest proto.InternalMessageInfo

type ResetResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetResponse) Reset()         { *m = ResetResponse{} }
func (m *ResetResponse) String() string { return proto.CompactTextString(m) }
func (*ResetResponse) ProtoMessage()    {}
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{6}
}
func (m *ResetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetResponse.Unmarshal(m, b)
}
func (m *ResetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetResponse.Marshal(b, m, deterministic)
}
func (m *ResetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetResponse.Merge(m, src)
}
func (m *ResetResponse) XXX_Size() int {
	return xxx_messageInfo_ResetResponse.Size(m)
}
func (m *ResetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetResponse proto.InternalMessageInfo

func (m *ResetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PendingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingRequest) Reset()         { *m = PendingRequest{} }
func (m *PendingRequest) String() string { return proto.CompactTextString(m) }
func (*PendingRequest) ProtoMessage()    {}
func (*PendingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{7}
}
func (m *PendingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingRequest.Unmarshal(m, b)
}
func (m *PendingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingRequest.Marshal(b, m, deterministic)
}
func (m *PendingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingRequest.Merge(m, src)
}
func (m *PendingRequest) XXX_Size() int {
	return xxx_messageInfo_PendingRequest.Size(m)
}
func (m *PendingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PendingRequest proto.InternalMessageInfo

type PendingResponse struct {
	Txs                  [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendingResponse) Reset()         { *m = PendingResponse{} }
func (m *PendingResponse) String() string { return proto.CompactTextString(m) }
func (*PendingResponse) ProtoMessage()    {}
func (*PendingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{8}
}
func (m *PendingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingResponse.Unmarshal(m, b)
}
func (m *PendingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingResponse.Marshal(b, m, deterministic)
}
func (m *PendingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingResponse.Merge(m, src)
}
func (m *PendingResponse) XXX_Size() int {
	return xxx_messageInfo_PendingResponse.Size(m)
}
func (m *PendingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PendingResponse proto.InternalMessageInfo

func (m *PendingResponse) GetTxs() [][]byte {
	if m != nil {
		return m.Txs
	}
	return nil
}

type BlockRequest struct {
	BlockHash            []byte   `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNum             uint64   `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{9}
}
func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequest.Unmarshal(m, b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequest.Marshal(b, m, deterministic)
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return xxx_messageInfo_BlockRequest.Size(m)
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *BlockRequest) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

type BlockResponse struct {
	BlockData            []byte   `protobuf:"bytes,1,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{10}
}
func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetBlockData() []byte {
	if m != nil {
		return m.BlockData
	}
	return nil
}

type BalanceRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlockNum             []byte   `protobuf:"bytes,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{11}
}
func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *BalanceRequest) GetBlockNum() []byte {
	if m != nil {
		return m.BlockNum
	}
	return nil
}

type BalanceResponse struct {
	Balance              []byte   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{12}
}
func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

type NonceRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	BlockNum             []byte   `protobuf:"bytes,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceRequest) Reset()         { *m = NonceRequest{} }
func (m *NonceRequest) String() string { return proto.CompactTextString(m) }
func (*NonceRequest) ProtoMessage()    {}
func (*NonceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{13}
}
func (m *NonceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceRequest.Unmarshal(m, b)
}
func (m *NonceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceRequest.Marshal(b, m, deterministic)
}
func (m *NonceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceRequest.Merge(m, src)
}
func (m *NonceRequest) XXX_Size() int {
	return xxx_messageInfo_NonceRequest.Size(m)
}
func (m *NonceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonceRequest proto.InternalMessageInfo

func (m *NonceRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *NonceRequest) GetBlockNum() []byte {
	if m != nil {
		return m.BlockNum
	}
	return nil
}

type NonceResponse struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonceResponse) Reset()         { *m = NonceResponse{} }
func (m *NonceResponse) String() string { return proto.CompactTextString(m) }
func (*NonceResponse) ProtoMessage()    {}
func (*NonceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{14}
}
func (m *NonceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonceResponse.Unmarshal(m, b)
}
func (m *NonceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonceResponse.Marshal(b, m, deterministic)
}
func (m *NonceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonceResponse.Merge(m, src)
}
func (m *NonceResponse) XXX_Size() int {
	return xxx_messageInfo_NonceResponse.Size(m)
}
func (m *NonceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NonceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NonceResponse proto.InternalMessageInfo

func (m *NonceResponse) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type LatestHeaderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestHeaderRequest) Reset()         { *m = LatestHeaderRequest{} }
func (m *LatestHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*LatestHeaderRequest) ProtoMessage()    {}
func (*LatestHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{15}
}
func (m *LatestHeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestHeaderRequest.Unmarshal(m, b)
}
func (m *LatestHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestHeaderRequest.Marshal(b, m, deterministic)
}
func (m *LatestHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestHeaderRequest.Merge(m, src)
}
func (m *LatestHeaderRequest) XXX_Size() int {
	return xxx_messageInfo_LatestHeaderRequest.Size(m)
}
func (m *LatestHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LatestHeaderRequest proto.InternalMessageInfo

type LatestHeaderResponse struct {
	BlockNum             []byte   `protobuf:"bytes,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	HeaderJson           []byte   `protobuf:"bytes,2,opt,name=header_json,json=headerJson,proto3" json:"header_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestHeaderResponse) Reset()         { *m = LatestHeaderResponse{} }
func (m *LatestHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*LatestHeaderResponse) ProtoMessage()    {}
func (*LatestHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{16}
}
func (m *LatestHeaderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestHeaderResponse.Unmarshal(m, b)
}
func (m *LatestHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestHeaderResponse.Marshal(b, m, deterministic)
}
func (m *LatestHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestHeaderResponse.Merge(m, src)
}
func (m *LatestHeaderResponse) XXX_Size() int {
	return xxx_messageInfo_LatestHeaderResponse.Size(m)
}
func (m *LatestHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestHeaderResponse proto.InternalMessageInfo

func (m *LatestHeaderResponse) GetBlockNum() []byte {
	if m != nil {
		return m.BlockNum
	}
	return nil
}

func (m *LatestHeaderResponse) GetHeaderJson() []byte {
	if m != nil {
		return m.HeaderJson
	}
	return nil
}

type CurrentBlockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentBlockRequest) Reset()         { *m = CurrentBlockRequest{} }
func (m *CurrentBlockRequest) String() string { return proto.CompactTextString(m) }
func (*CurrentBlockRequest) ProtoMessage()    {}
func (*CurrentBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{17}
}
func (m *CurrentBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentBlockRequest.Unmarshal(m, b)
}
func (m *CurrentBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentBlockRequest.Marshal(b, m, deterministic)
}
func (m *CurrentBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentBlockRequest.Merge(m, src)
}
func (m *CurrentBlockRequest) XXX_Size() int {
	return xxx_messageInfo_CurrentBlockRequest.Size(m)
}
func (m *CurrentBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentBlockRequest proto.InternalMessageInfo

type CurrentBlockResponse struct {
	BlockData            []byte   `protobuf:"bytes,1,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentBlockResponse) Reset()         { *m = CurrentBlockResponse{} }
func (m *CurrentBlockResponse) String() string { return proto.CompactTextString(m) }
func (*CurrentBlockResponse) ProtoMessage()    {}
func (*CurrentBlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{18}
}
func (m *CurrentBlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurrentBlockResponse.Unmarshal(m, b)
}
func (m *CurrentBlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurrentBlockResponse.Marshal(b, m, deterministic)
}
func (m *CurrentBlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentBlockResponse.Merge(m, src)
}
func (m *CurrentBlockResponse) XXX_Size() int {
	return xxx_messageInfo_CurrentBlockResponse.Size(m)
}
func (m *CurrentBlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentBlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentBlockResponse proto.InternalMessageInfo

func (m *CurrentBlockResponse) GetBlockData() []byte {
	if m != nil {
		return m.BlockData
	}
	return nil
}

type ChainHeadEventRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainHeadEventRequest) Reset()         { *m = ChainHeadEventRequest{} }
func (m *ChainHeadEventRequest) String() string { return proto.CompactTextString(m) }
func (*ChainHeadEventRequest) ProtoMessage()    {}
func (*ChainHeadEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{19}
}
func (m *ChainHeadEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainHeadEventRequest.Unmarshal(m, b)
}
func (m *ChainHeadEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainHeadEventRequest.Marshal(b, m, deterministic)
}
func (m *ChainHeadEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainHeadEventRequest.Merge(m, src)
}
func (m *ChainHeadEventRequest) XXX_Size() int {
	return xxx_messageInfo_ChainHeadEventRequest.Size(m)
}
func (m *ChainHeadEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainHeadEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChainHeadEventRequest proto.InternalMessageInfo

type ChainHeadEventResponse struct {
	BlockData            []byte   `protobuf:"bytes,1,opt,name=block_data,json=blockData,proto3" json:"block_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainHeadEventResponse) Reset()         { *m = ChainHeadEventResponse{} }
func (m *ChainHeadEventResponse) String() string { return proto.CompactTextString(m) }
func (*ChainHeadEventResponse) ProtoMessage()    {}
func (*ChainHeadEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec141b309055405, []int{20}
}
func (m *ChainHeadEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainHeadEventResponse.Unmarshal(m, b)
}
func (m *ChainHeadEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainHeadEventResponse.Marshal(b, m, deterministic)
}
func (m *ChainHeadEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainHeadEventResponse.Merge(m, src)
}
func (m *ChainHeadEventResponse) XXX_Size() int {
	return xxx_messageInfo_ChainHeadEventResponse.Size(m)
}
func (m *ChainHeadEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainHeadEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChainHeadEventResponse proto.InternalMessageInfo

func (m *ChainHeadEventResponse) GetBlockData() []byte {
	if m != nil {
		return m.BlockData
	}
	return nil
}

func init() {
	proto.RegisterType((*HealthCheckResponse)(nil), "trusted.v1.HealthCheckResponse")
	proto.RegisterType((*AddTxRequest)(nil), "trusted.v1.AddTxRequest")
	proto.RegisterType((*AddTxResponse)(nil), "trusted.v1.AddTxResponse")
	proto.RegisterType((*StatusRequest)(nil), "trusted.v1.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "trusted.v1.StatusResponse")
	proto.RegisterType((*ResetRequest)(nil), "trusted.v1.ResetRequest")
	proto.RegisterType((*ResetResponse)(nil), "trusted.v1.ResetResponse")
	proto.RegisterType((*PendingRequest)(nil), "trusted.v1.PendingRequest")
	proto.RegisterType((*PendingResponse)(nil), "trusted.v1.PendingResponse")
	proto.RegisterType((*BlockRequest)(nil), "trusted.v1.BlockRequest")
	proto.RegisterType((*BlockResponse)(nil), "trusted.v1.BlockResponse")
	proto.RegisterType((*BalanceRequest)(nil), "trusted.v1.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "trusted.v1.BalanceResponse")
	proto.RegisterType((*NonceRequest)(nil), "trusted.v1.NonceRequest")
	proto.RegisterType((*NonceResponse)(nil), "trusted.v1.NonceResponse")
	proto.RegisterType((*LatestHeaderRequest)(nil), "trusted.v1.LatestHeaderRequest")
	proto.RegisterType((*LatestHeaderResponse)(nil), "trusted.v1.LatestHeaderResponse")
	proto.RegisterType((*CurrentBlockRequest)(nil), "trusted.v1.CurrentBlockRequest")
	proto.RegisterType((*CurrentBlockResponse)(nil), "trusted.v1.CurrentBlockResponse")
	proto.RegisterType((*ChainHeadEventRequest)(nil), "trusted.v1.ChainHeadEventRequest")
	proto.RegisterType((*ChainHeadEventResponse)(nil), "trusted.v1.ChainHeadEventResponse")
}

func init() { proto.RegisterFile("trusted/v1/request_response.proto", fileDescriptor_8ec141b309055405) }

var fileDescriptor_8ec141b309055405 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x6f, 0x6b, 0xd3, 0x50,
	0x14, 0xc6, 0x49, 0x5b, 0xf7, 0xe7, 0x2c, 0x6d, 0x47, 0xd7, 0xd5, 0x32, 0x91, 0xd5, 0xc8, 0xa4,
	0x20, 0x36, 0x04, 0x11, 0x61, 0x22, 0x68, 0xbb, 0xb1, 0x32, 0x74, 0x94, 0x58, 0xca, 0x90, 0x41,
	0xb9, 0x6d, 0x4e, 0x9b, 0xb8, 0x24, 0xb7, 0xcb, 0xbd, 0x29, 0xfd, 0x3c, 0xbe, 0xf4, 0xbd, 0x5f,
	0xc2, 0x8f, 0xe1, 0x4b, 0x3f, 0x85, 0xdc, 0xdc, 0x9b, 0xa4, 0x9d, 0x6f, 0x06, 0xbe, 0xcb, 0x73,
	0xee, 0x73, 0x9e, 0xdf, 0xe1, 0xdc, 0x70, 0xe1, 0x19, 0x8f, 0x62, 0xc6, 0xd1, 0x31, 0x97, 0x96,
	0x19, 0xe1, 0x5d, 0x8c, 0x8c, 0x8f, 0x23, 0x64, 0x0b, 0x1a, 0x32, 0xec, 0x2c, 0x22, 0xca, 0x69,
	0x0d, 0x94, 0xa5, 0xb3, 0xb4, 0x8e, 0x5a, 0x73, 0x4a, 0xe7, 0x3e, 0x9a, 0xc9, 0xc9, 0x24, 0x9e,
	0x99, 0x33, 0x0f, 0x7d, 0x67, 0x1c, 0x10, 0x76, 0x2b, 0xdd, 0x47, 0xc7, 0xf7, 0x1d, 0xdc, 0x0b,
	0x90, 0x71, 0x12, 0x2c, 0xa4, 0xc1, 0xe8, 0xc1, 0x41, 0x1f, 0x89, 0xcf, 0xdd, 0x9e, 0x8b, 0xd3,
	0x5b, 0x5b, 0xb1, 0x6a, 0x0d, 0xd8, 0x62, 0x9c, 0xf0, 0x98, 0x35, 0xb5, 0x96, 0xd6, 0xde, 0xb1,
	0x95, 0xaa, 0xd5, 0xe1, 0x11, 0x46, 0x11, 0x8d, 0x9a, 0x85, 0x96, 0xd6, 0xd6, 0x6d, 0x29, 0x8c,
	0x17, 0xa0, 0x7f, 0x74, 0x9c, 0xe1, 0xca, 0x96, 0x23, 0x8b, 0x6e, 0xbe, 0x72, 0x08, 0x27, 0x49,
	0xb7, 0x6e, 0x2b, 0x65, 0xbc, 0x87, 0xb2, 0xf2, 0xe5, 0x18, 0xbe, 0x72, 0x09, 0x73, 0x73, 0xa3,
	0x50, 0x9b, 0x98, 0xdd, 0x14, 0x53, 0x85, 0xf2, 0x97, 0x64, 0x0c, 0xc5, 0x31, 0x3e, 0x40, 0x25,
	0x2d, 0xa8, 0xc0, 0x26, 0x6c, 0x2f, 0x30, 0x74, 0xbc, 0x70, 0x9e, 0x24, 0x96, 0xec, 0x54, 0x8a,
	0xc8, 0xbb, 0x18, 0x63, 0x4c, 0x22, 0x4b, 0xb6, 0x14, 0x46, 0x05, 0x74, 0x1b, 0x19, 0xf2, 0x34,
	0xf1, 0x04, 0xca, 0x4a, 0xab, 0xc0, 0x6c, 0x12, 0x6d, 0x7d, 0x92, 0x7d, 0xa8, 0x0c, 0x64, 0x6e,
	0xda, 0xf8, 0x1c, 0xaa, 0x59, 0x45, 0xb5, 0xee, 0x43, 0x91, 0xaf, 0xc4, 0x02, 0x8b, 0x6d, 0xdd,
	0x16, 0x9f, 0xc6, 0x25, 0xe8, 0x5d, 0x9f, 0x8a, 0x35, 0xcb, 0x3d, 0x3d, 0x05, 0x98, 0x08, 0x3d,
	0x5e, 0x5b, 0xc1, 0x6e, 0x52, 0xe9, 0x8b, 0x2d, 0x3c, 0x01, 0x29, 0xc6, 0x61, 0x1c, 0xa8, 0xb1,
	0x77, 0x92, 0xc2, 0x55, 0x1c, 0x18, 0x1d, 0x28, 0xab, 0x2c, 0x85, 0xcb, 0xc2, 0xd6, 0x16, 0x2f,
	0xfb, 0xcf, 0xc4, 0xee, 0x2f, 0xa0, 0xd2, 0x25, 0x3e, 0x09, 0xa7, 0x98, 0xd2, 0x9b, 0xb0, 0x4d,
	0x1c, 0x27, 0x42, 0xc6, 0x94, 0x3b, 0x95, 0xff, 0x82, 0xf5, 0x35, 0xf0, 0x4b, 0xa8, 0x66, 0x41,
	0xf9, 0xd6, 0x27, 0xb2, 0x94, 0x26, 0x29, 0x69, 0x9c, 0x83, 0x7e, 0x45, 0xff, 0x9f, 0x79, 0x02,
	0x65, 0x15, 0x93, 0x5f, 0x4b, 0x48, 0x53, 0x5e, 0xc9, 0x96, 0xc2, 0x38, 0x84, 0x83, 0x4f, 0x84,
	0x23, 0xe3, 0x7d, 0x24, 0x0e, 0x46, 0xe9, 0xdd, 0x0c, 0xa1, 0xbe, 0x59, 0x56, 0x21, 0x1b, 0x48,
	0x6d, 0x13, 0x59, 0x3b, 0x86, 0x3d, 0x37, 0xb1, 0x8f, 0xbf, 0x31, 0x1a, 0xaa, 0x89, 0x40, 0x96,
	0x2e, 0x19, 0x0d, 0x05, 0xac, 0x17, 0x47, 0x11, 0x86, 0x7c, 0xfd, 0x4e, 0x8d, 0x37, 0x50, 0xdf,
	0x2c, 0x3f, 0xec, 0x7a, 0x1e, 0xc3, 0x61, 0xcf, 0x25, 0x5e, 0x28, 0x46, 0x3c, 0x5f, 0x62, 0x98,
	0xfd, 0x91, 0x6f, 0xa1, 0x71, 0xff, 0xe0, 0x41, 0x89, 0xdd, 0x9f, 0x1a, 0x54, 0xa6, 0x34, 0xe8,
	0xe4, 0xef, 0x45, 0xb7, 0xae, 0x42, 0xd3, 0x88, 0x81, 0x78, 0x02, 0x06, 0xda, 0xd7, 0xb3, 0xb9,
	0xc7, 0xdd, 0x78, 0xd2, 0x99, 0xd2, 0xc0, 0x54, 0xf6, 0x57, 0x0e, 0xce, 0xbc, 0x4c, 0xf0, 0xd5,
	0x82, 0x52, 0x5f, 0xbe, 0x22, 0x53, 0xea, 0x9b, 0xf9, 0x33, 0xf5, 0x4e, 0x7d, 0x2e, 0xad, 0xef,
	0x85, 0xe2, 0xf0, 0xfa, 0xfa, 0x47, 0x01, 0x86, 0x0a, 0x38, 0xb2, 0x7e, 0x65, 0xe2, 0x66, 0x64,
	0xfd, 0x2e, 0x34, 0x72, 0x71, 0x73, 0x31, 0xe8, 0x7e, 0x46, 0x4e, 0xc4, 0xe8, 0x7f, 0x0a, 0x7b,
	0xea, 0xe0, 0xf4, 0x74, 0x64, 0x4d, 0xb6, 0x12, 0xca, 0xeb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0xfb, 0x7e, 0x4c, 0x0c, 0x05, 0x00, 0x00,
}
